version: "3.7"

services: 
    apache:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - ./:/var/www/html/
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
        ports: 
            - 8001:80
        networks: 
            bolinggo:
                aliases: 
                    - cdn.bolinggo.id

networks:
    bolinggo:
        name: 'bolinggo'
            